# Generated by Django 6.0.6 on 2026-06-23 11:09

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingProvider',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Provider Verification',
                'verbose_name_plural': 'Pending Provider Verifications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
