# Generated by Django 6.0.6 on 2026-06-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_patientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='patients/photos/'),
        ),
    ]
