# Generated by Django 6.0.6 on 2026-06-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_doctorpatientrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpatientrelation',
            name='allergies_intolerances',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorpatientrelation',
            name='current_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorpatientrelation',
            name='current_medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorpatientrelation',
            name='health_goals',
            field=models.TextField(blank=True, null=True),
        ),
    ]
