# Generated by Django 6.0.6 on 2026-06-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_doctorpatientrelation_allergies_intolerances_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorpatientrelation',
            name='todays_progress',
        ),
    ]
