# Generated by Django 6.0.6 on 2026-06-27 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='appointments.protocol')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('protocol', 'date')},
            },
        ),
    ]
